main/urls.py
from django.urls import path
from . import views

app_name = "main"

# acts like a controller

urlpatterns = [
    #homepage
    path("", views.homepage, name = "homepage"), #homepage function in view
    path("register/", views.register, name="register"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("videos/", views.video_list, name="video_list"),
    path("videos/upload/", views.upload_video, name="upload_video"),
    path("graph/", views.graph, name="graph")
]

usersite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),

]

# if the app in the debug mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import  datetime
from django.conf import settings
# Create your models here.
# All models will be inherited from Django base model

# each model will map to database's table

# user model
class CrowdDensity(models.Model):
    #define the columns of the database
    user_dashboard_title = models.CharField(max_length=200) # set a fixed field
    user_dashboard_content = models.TextField()
    user_dashboard_published = models.DateTimeField("date published", default=datetime.now)


    # override string method
    def __str__(self):
        return self.user_dashboard_title

# user report model
class GraphCategory(models.Model):
    graph_category = models.CharField(max_length=200)
    category_summary = models.CharField(max_length=200)
    category_slug = models.CharField(max_length=200, default=1) # for the url

    class Meta:
        verbose_name_plural = "Categories"
    def __str__(self):
        return  self.graph_category

# video model
class Footage(models.Model):

    video_title = models.CharField(max_length=100)
    upload_date = models.DateTimeField("date uploaded", default=datetime.now)
    video = models.FileField(upload_to='videos/', null=True)

    # override string method
    def __str__(self):
        return self.video_title

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Footage

class NewUserForm(UserCreationForm): #inherit from UserCreationForm
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    # when the form got saved
    def save(self, commit=True): # commit data, chuck in the db
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class FootageForm(forms.ModelForm):
    class Meta:
        model = Footage
        fields = ('video_title', 'upload_date', 'video')

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from main.models import CrowdDensity
from .forms import NewUserForm
from django.core.files.storage import FileSystemStorage
from .forms import FootageForm
from .models import Footage
from plotly.offline import plot
import plotly.graph_objs as go

from .tasks import create_db_csv


import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import operator

# Create your views here.

# Business logic here

# render homepage
def homepage(request):

    return render(request= request,
                  template_name="main/home.html",
                  context={"users": CrowdDensity.objects.all},)

#graph page for graph showing
def graph(request):

    if chkProcessing():
        msg = "Footage is processing, the graphs will be update after process is finished"
    else:
        msg = "Footage processing is finished"

    data = plotgraph()
    x_data = data['predict_time']
    y_data = data['predict_num']

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=x_data,
        y=y_data,
        line=dict(color='green')
    ))
    fig.update_layout(
        title="Forecast data of number of people vs time",
        xaxis_title="time",
        yaxis_title="ppl no.",
        height=500
    )
    predict_plot_div = plot(fig, output_type='div')

    # do for loop for collected data plotting
    collected = data['collected']
    collected_plot_divs = []

    for date in collected:
        time = collected[date]['time']
        num = (collected[date])['num']

        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=time,
            y=num,
            line=dict(color='blue')
        ))
        fig.update_layout(
            title=date,
            xaxis_title="time",
            yaxis_title="ppl no.",
            height=500
        )

        this_plot_div = plot(fig, output_type='div')
        collected_plot_divs.append(this_plot_div)

    return render(request, "main/graph.html", context={'more': data['more_cus'],
                                                       'less': data['less_cus'],
                                                       'predict_plot_div': predict_plot_div,
                                                       'collected_plot_divs': collected_plot_divs,
                                                       'status': msg
                                                       })


# render register page as well as its function
def register(request):
    # handle the post request
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username') # normalize the name to consistent format
            messages.success(request,  f"New account created: {username}")
            login(request, user)
            messages.info(request, f"You are now logged in as: {username}")
            # if user finished registering, redirect to another page
            return redirect("main:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

            # re-render the form
            return render(request=request,
                          template_name="main/register.html",
                          context={"form": form})

    #re render the user form
    form = NewUserForm
    return render(request, "main/register.html", context={"form": form})

# render logout request
def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("main:homepage")

# render login page as well as its function
def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)

        # check if the form is valid
        if form.is_valid():
            # get hold of the text field
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            # authenticate the user
            user = authenticate(username = username, password = password)
            # check if the user is authenticated
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as: {username}")
                return redirect("main:homepage")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")

    form = AuthenticationForm()
    return render(request, "main/login.html", {"form": form})



def video_list(request):

    if chkProcessing():
        msg = "Footage is processing"
    else:
        msg = "Footage processing is finished"

    videos = Footage.objects.all()
    return render(request, 'main/video_list.html', {
        'videos': videos,
        'status': msg
    })

def upload_video(request):
    global isProcessing
    global processStatus

    if request.method == "POST":
        form = FootageForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()

            # start to read vid file
            processStatus = create_db_csv.delay()

            return redirect('main:video_list')
    else:
        form = FootageForm()
    return render(request, 'main/upload_video.html', {
        'form': form
    })

def plotgraph():
    projectDir = os.path.dirname(os.path.realpath(__file__))

    # set up time for column name
    col_name = []
    for h in range(24):
        for m in range(60):
            if (m % 10 == 0):
                if (m == 0):
                    col_name.append(str(h) + ':00')
                else:
                    col_name.append(str(h) + ':' + str(m))

    # set business start hour and end hour
    start_h = 17
    end_h = 22

    starth_index = col_name.index(str(start_h) + ':00')
    endh_index = col_name.index(str(end_h) + ':00')
    endh_index += 1

    # import csv file
    df = pd.read_csv(r'' + projectDir + '/csv/db.csv')
    daysName = df['Date'].tolist()

    # delete date column
    df = df.drop(columns=['Date'])

    # create the list of the day which data collected
    days = pd.DataFrame(list(range(1, df.shape[0] + 1)), columns=['day'])
    # df = df.set_index('Date')

    # train the system which X is the day and Y is the number of ppl in each period
    X_train, X_test, y_train, y_test = train_test_split(days, df, test_size=0.2, random_state=5)

    # model instantiation
    lm = LinearRegression()

    # fitting model for each time period then add to predict list
    predict_list = []
    trending_list = []
    score_list = []

    for period in col_name:
        lm.fit(X_train, y_train[period])
        predict_val = lm.predict([[df.shape[0] + 1]])
        if predict_val >= 0:
            predict_list.append(predict_val[0])
        else:
            predict_list.append(0)
        trending_list.append(lm.coef_[0])
        score_list.append(lm.score(X_test, y_test[period]))

    # print(score_list)

    # Looking for beta value which shows the trend of number in future
    index_max, value_max = max(enumerate(trending_list), key=operator.itemgetter(1))
    index_min, value_min = min(enumerate(trending_list), key=operator.itemgetter(1))

    # Match with the period of time
    #print("The period which most tend to have more customer ", col_name[index_max])
    #print("The period which most tend to lost customer ", col_name[index_min])

    # creat data dictionary to return
    return_data = {}
    return_data['more_cus'] = col_name[index_max]
    return_data['less_cus'] = col_name[index_min]

    # get the prediction data
    return_data['predict_time'] = col_name[starth_index:endh_index]
    return_data['predict_num'] = predict_list[starth_index:endh_index]

    # do the loop to get collected data
    collected_data = {}
    for i in range(df.shape[0]):
        collected_data[daysName[i]] = {'time' : col_name[starth_index:endh_index], 'num':df.iloc[i][starth_index:endh_index]}

    return_data['collected'] = collected_data
    return return_data


def chkProcessing():
    # chk temp folder to check status of file processing
    projectDir = os.path.dirname(os.path.realpath(__file__))

    if 'isProcessing' in os.listdir(projectDir + '/temps/'):
        return True
    else:
        return False

main/templates/main/graph.html
{%  extends "main/header.html" %}
{% block content %}
 <div class="row">
    <h1>Crowd analysis for the business</h1>
    <h4> {{ status }} </h4>
    {% autoescape off %}
    {{ predict_plot_div }}
    {% endautoescape %}
    <h2>Trending information</h2>
    <p>The period which most tend to have more customer is : {{ more }}</p>
    <p>The period which most tend to lost customer is : {{ less }}</p>
    <h2>Collected data</h2>
    {%  for collected_plot_div in collected_plot_divs %}
        {% autoescape off %}
        {{ collected_plot_div }}
        {% endautoescape %}
    {% endfor %}
 </div>
{% endblock %}

main/templates/main/header.html
{% load static %}
<head>
    {% load static %}
    <link href="{% static 'main/css/materialize.css' %}" rel="stylesheet">
   <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript for Materialize CSS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>

{% include "main/includes/navbar.html" %}
{% include "main/includes/messages.html" %}

<div class="container">
    <br>
    {% block content %}
    {% endblock %}
</div>
</body>

main/templates/main/home.html
{%  extends "main/header.html" %}

{% block content %}
<div class="row">

        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">Welcome to Crowd Analysis, {{user.username|title}}</span>
                  <p style="font-size: 70%">{{user.user_dashboard_published}}</p>
                  <p>{{tut.user_dashboard_content|safe}}</p>
            </div>
            <div class="card-action">
             {% if user.is_authenticated %}
                  <a href="/videos/upload">Upload your videos</a>
                  <a href="/graph">Show Graph</a>
               {% else %}
                  <a href="/videos/upload"></a>
               {% endif %}
            </div>
          </div>
        </div>

</div>
{% endblock %}

main/templates/main/login.html
{%  extends "main/header.html" %}

{% block content %}
    <form method="POST">
    <!-- aim to combat something called Cross Site Request Forgery-->
        {% csrf_token %}
        <!--build the form from django and chuck it in here-->
        {{ form.as_p }}
        <button class="btn" style="background-color: palevioletred" type="submit">Login</button>
    </form>
    If you don't already have an account, <a href="/register"><strong>Register</strong></a> instead.
{% endblock %}

main/templates/main/register.html
{%  extends "main/header.html" %}

{% block content %}
    <form method="POST">
    <!-- aim to combat something called Cross Site Request Forgery-->
        {% csrf_token %}
        <!--build the form from django and chuck it in here-->
        {{ form.as_p }}
        <button class="btn" style="background-color: palevioletred" type="submit">Register</button>
    </form>
    If you already have an account, <a href="login"><strong>Login</strong></a> instead.
{% endblock %}

main/templates/main/upload_video.html
{%  extends "main/header.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <h2>Upload</h2>
    <a href="{% url 'main:video_list'%}" class="btn btn-primary btn-sm">Video List</a>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit", class="btn btn-primary">Upload Video</button>
    </form>
</div>
{% endblock %}

main/templates/main/video_list.html
{%  extends "main/header.html" %}

{% block content %}
<div class="row">
    <h2>Video List</h2>
    <p>
        <a href="{% url 'main:upload_video'%}" class="btn btn-primary btn-sm">Upload Videos</a>
        <h6><a><p> {{ status }} </p></a></h6>

    </p>
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Upload date</th>
                <th>Download</th>
            </tr>
        </thead>
        <tbody>
            {%  for video in videos %}
                <tr>
                    <td>{{ video.video_title }}</td>
                    <td>{{ video.upload_date }}</td>
                    <td>
                        <a href="{{ video.video }}" class="btn btn-primary btn-sm" target="_blank">Download Video</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}